### ISSUE TITLE
Problem with python versions

### ISSUE THREAD

**Issue by seivazi** [patrosAT/human_robot_handover_ros#1]
I noticed about different python versions (2.7 vs 3) in your project. 
Could you explain how did you deal with that?

**Comment by patrosAT** [comment]
Yes, we use both python 2.7 and 3. To speed up response time (time between image capturing and system/robot arm response), we host each module on a different computer that uses either python 2.7 or python 3.

Is this the answer you were looking for?

**Comment by seivazi** [comment]
Thanks for your fast reply. How did you use ROS and python 3 together? are you using Melodic?

**Comment by patrosAT** [comment]
Yes, we use Melodic and pyhton 3 together. Only “cv_bridge” does not work in combination with python 3 so we use “ros_numpy” for messaging instead.

**Comment by seivazi** [comment]
Thanks for the hint. I will try the same.
