### ISSUE TITLE
About the customized gripper 

### ISSUE THREAD

**Issue by bearpaw** [patrosAT/human_robot_handover_ros#2]
Thanks @patrosAT for sharing this great code! I was wondering if the CAD model for the custom-made finger molds is also available? Thanks in advance!

> To increase the grasp robustness, we used custom-made gripper jaw surfaces made of silicon rubber that are
based on [18]. Fully open, the gripper can pick objects with
a maximal width of 7cm.

**Comment by patrosAT** [comment]
Hi @bearpaw, unfortunately I do not. Maybe reference [18] can help you.

**Comment by bearpaw** [comment]
Thanks for your quick response! Sorry, I think my question was not clear. 

I understand the surface material can be found in [18]. My question is more on the Franka finger design: in the experiments, you seem to extend the fingers for the Franka gripper compared to the original fingers (see images). It looks very interesting and good for grasping tasks. I was wondering did you design and made the fingers yourself? Or can you point to me if this is from somewhere else? Thanks!

![image](https://user-images.githubusercontent.com/289501/117337861-bf99a180-ae52-11eb-876a-714129cc89a0.png)
![image](https://user-images.githubusercontent.com/289501/117337932-d3dd9e80-ae52-11eb-84ad-c64eb81ef9ba.png)

**Comment by patrosAT** [comment]
Please have a look a source [18]. You can find the PDF under the following link:
https://goldberg.berkeley.edu/pubs/Gripper-Tip-Design-ICRA-under-review-September-2017.pdf

Therein you will find detailed information about the silicone gripper tips (design, material, shape). Nevertheless, I am not able to provide you with a CAD model.
